/*
 * File: app/mundialito/store/gmo/gmu/utiles/sttipodocidentidad.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.store.gmo.gmu.utiles.sttipodocidentidad', {
    extend: 'Ext.data.Store',

    alternateClassName: [
        'gmo.gmu.utiles.sttipodocidentidad'
    ],
    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'gmo.gmu.utiles.sttipodocidentidad',
            data: [
                {
                    tpo_codigo: 1,
                    tpo_descripcion: 'DNI'
                },
                {
                    tpo_codigo: 2,
                    tpo_descripcion: 'RUT'
                },
                {
                    tpo_codigo: 3,
                    tpo_descripcion: 'PASAPORTE'
                }
            ],
            fields: [
                {
                    name: 'tpo_codigo',
                    type: 'int'
                },
                {
                    name: 'tpo_descripcion',
                    type: 'string'
                }
            ]
        }, cfg)]);
    }
});