/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    models: [
        'gmo.gmu.registro.mdregistro',
        'gmo.gmu.grupodetreg.mdgrupodetreg',
        'gmo.gmu.partidoreg.mdpartidoreg',
        'gmo.gmu.partidoreg.mdpartidoreggrupo',
        'gmo.gmu.adicionalreg.mdadicionalreg',
        'gmo.gmu.excelenciareg.mdexcelenciareg',
        'gmo.gmu.jugador.mdjugador',
        'gmo.gmu.persona.mdpersona',
        'gmo.gmu.resultado.mdresultado',
        'gmo.gmu.resultado.mdresumen'
    ],
    stores: [
        'gmo.gmu.registro.stregistro',
        'gmo.gmu.grupodetreg.stgrupodetreg',
        'gmo.gmu.partidoreg.stpartidoreg',
        'gmo.gmu.partidoreg.stpartidoregcuarto',
        'gmo.gmu.partidoreg.stpartidoregfinal',
        'gmo.gmu.partidoreg.stpartidoreggrupo',
        'gmo.gmu.utiles.stpais',
        'gmo.gmu.adicionalreg.stadicionalreg',
        'gmo.gmu.excelenciareg.stexcelenciareg',
        'gmo.gmu.adicionalreg.stadicionalreggrupo',
        'gmo.gmu.excelenciareg.stexcelenciareggrupo',
        'gmo.gmu.jugador.stjugador',
        'gmo.gmu.persona.stpersona',
        'gmo.gmu.resultado.stresultado',
        'gmo.gmu.resultado.rsresumen'
    ],
    views: [
        'gmo.gmu.registro.vpmain',
        'gmo.gmu.persona.winMtto',
        'gmo.gmu.autenticacion.winMtto',
        'gmo.gmu.registro.winMtto',
        'gmo.gmu.jugador.winListado',
        'gmo.gmu.security.winchangepwd'
    ],
    appFolder: 'app/mundialito',
    appProperty: 'mundialito',
    controllers: [
        'gmo.gmu.registro.ctrMain',
        'gmo.gmu.partidoreg.crtMtto',
        'gmo.gmu.autenticacion.ctrMtto',
        'gmo.gmu.persona.ctrMtto',
        'gmo.gmu.registro.ctrMtto',
        'gmo.gmu.adicionalreg.ctrMtto',
        'gmo.gmu.excelenciareg.ctrMtto',
        'gmo.gmu.jugador.ctrlistado',
        'gmo.gmu.utiles.ctrfuncion',
        'gmo.gmu.security.ctrMtto'
    ],
    name: 'mundialito',
    title: 'GMO - Mundialito',

    launch: function() {
        Ext.create('mundialito.view.gmo.gmu.autenticacion.winMtto', {renderTo: Ext.getBody()});
    }

});
