/*
 * File: app/mundialito/model/gmo/gmu/persona/mdpersona.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.model.gmo.gmu.persona.mdpersona', {
    extend: 'Ext.data.Model',

    alternateClassName: [
        'gmo.gmu.persona.mdpersona'
    ],
    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ln_per_codigo',

    fields: [
        {
            name: 'ln_per_codigo',
            type: 'int'
        },
        {
            name: 'ls_per_nombre',
            type: 'string'
        },
        {
            name: 'ln_tpo_codigo',
            type: 'int'
        },
        {
            name: 'ls_tpo_descripcion',
            type: 'string'
        },
        {
            name: 'ls_per_nrodocidentidad',
            type: 'string'
        },
        {
            name: 'ls_per_movil',
            type: 'string'
        },
        {
            name: 'ln_pai_codigo',
            type: 'int'
        },
        {
            name: 'ls_pai_denominacion',
            type: 'string'
        }
    ]
});