/*
 * File: app/mundialito/view/gmo/gmu/security/winchangepwd.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.security.winchangepwd', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.security.winchangepwd'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Hidden'
    ],

    height: 152,
    itemId: 'wingmuchangepwd',
    width: 297,
    title: 'Cambio Password',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Menu de opciones:'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            iconCls: 'btnSave',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCerrar',
                            iconCls: 'btnClose',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    height: 112,
                    itemId: 'frmgmuchangepwd',
                    width: 285,
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/Mundialito/process/lst_seg_cuenta.php',
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'ls_cta_password',
                            fieldLabel: 'Passwor Actual',
                            labelWidth: 120,
                            name: 'ls_cta_password',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'ls_cta_passwordnvo',
                            fieldLabel: 'Nuevo Password',
                            labelWidth: 120,
                            name: 'ls_cta_passwordnvo',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'ls_cta_passwordnvocon',
                            fieldLabel: 'Confirmar Password',
                            labelWidth: 120,
                            name: 'ls_cta_passwordnvocon',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_per_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_per_codigo'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});