/*
 * File: app/mundialito/view/gmo/gmu/autenticacion/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.autenticacion.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.autenticacion.winMtto'
    ],
    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.form.field.Display',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button'
    ],

    autoShow: true,
    height: 181,
    itemId: 'wingmuautenticacion',
    width: 412,
    closable: false,
    title: 'Autenticacion de Participante',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'frmgmuautenticacion',
                    method: 'POST',
                    url: '/library/Mundialito/process/lst_gmu_autenticacion.php',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Datos de cuenta de Acceso',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'ls_cta_usuario',
                                    fieldLabel: 'DNI | RUC:',
                                    name: 'ls_cta_usuario',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'ls_cta_password',
                                    fieldLabel: 'Password:',
                                    name: 'ls_cta_password',
                                    inputType: 'password',
                                    allowBlank: false,
                                    blankText: 'Ingresar Password'
                                }
                            ]
                        },
                        {
                            xtype: 'displayfield',
                            margin: '3 3 3 3',
                            value: 'Para poder ingresar previamente tiene que registrarse para que se le genere su cuenta de acceso.'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Menu de opciones:'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnSesion',
                                    iconCls: 'btnSesion',
                                    text: 'Aceptar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRegistrar',
                                    iconCls: 'btnNew',
                                    text: 'Registrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCerrar',
                                    iconCls: 'btnClose',
                                    text: 'Cerrar'
                                },
                                {
                                    xtype: 'tbseparator'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});