/*
 * File: app/mundialito/controller/gmo/gmu/security/ctrMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.controller.gmo.gmu.security.ctrMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gmu.security.ctrMtto'
    ],

    refs: [
        {
            ref: 'Mtto',
            selector: '#wingmuchangepwd'
        }
    ],

    onBtnGuardarClick: function(button, e, eOpts) {
                var me = this,
                    win = me.getMtto(),
                    pwd_nvo = win.down('#ls_cta_passwordnvo').getValue(),
                    pwd_con = win.down('#ls_cta_passwordnvocon').getValue(),
                    frm = win.down('#frmgmuchangepwd');

                    if (frm.isValid()===false){

                        Ext.MessageBox.alert('Mensaje','Datos de formulario incompleto');

                        return;
                    }

                 if (pwd_nvo!==pwd_con){

                        Ext.MessageBox.alert('Mensaje','Nueva clave ingresada no coinciden con la clave de confirmacion');

                        return;
                    }


                frm.submit({
                        success: function(form,action){

                            var objJson = Ext.JSON.decode(action.response.responseText);

                            if(objJson.success){

                                var ls_mensaje =objJson.data[0].ls_mensaje;

                                Ext.MessageBox.alert('Mensaje',ls_mensaje);

                            }

                        },

                         failure: function(form,action){

                            var objJson =Ext.JSON.decode(action.response.responseText);

                            Ext.MessageBox.alert('Mensaje',objJson.msgError);

                         },
                        params:{'operacion': 1}
                    });


    },

    onBtnCerrarClick: function(button, e, eOpts) {
                button.up('window').close();
    },

    init: function(application) {
        this.control({
            "#wingmuchangepwd #btnGuardar": {
                click: this.onBtnGuardarClick
            },
            "#wingmuchangepwd #btnCerrar": {
                click: this.onBtnCerrarClick
            }
        });
    }

});
