/*
 * File: app/mundialito/controller/gmo/gmu/persona/ctrMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.controller.gmo.gmu.persona.ctrMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gmu.persona.ctrMtto'
    ],

    stores: [
        'gmo.gmu.utiles.sttipodocidentidad'
    ],

    refs: [
        {
            ref: 'Mtto',
            selector: '#winglbpersona'
        },
        {
            ref: 'Logeo',
            selector: '#wingmuautenticacion'
        }
    ],

    onBtnguardarClick: function(button, e, eOpts) {
            var me=this,
                win = me.getMtto(),
                winlogeo = me.getLogeo(),
                ln_accion = win.down('#accion').getValue(),
                win_parent = win.down('#win_parent').getValue(),
                frm = win.down('#frmglbpersona');

            if (frm.isValid()===false) {

                Ext.MessageBox.alert('Mensaje','Datos de participante incompleto');

                return;
            }


            frm.submit({
                success: function(form, action){

                var objJson =Ext.JSON.decode(action.response.responseText);

                if (objJson.success){

                    var ls_mensaje=objJson.msg;

                    if (ln_accion==='1'){

                        Ext.MessageBox.alert('Mensaje',ls_mensaje+' '+', Su usuario y password sera su nro. de documento de identidad');

                    }else{

                            Ext.MessageBox.alert('Mensaje',ls_mensaje);
                        }

                        if (win_parent==='0'){

                            winlogeo.down('#ls_cta_usuario').setValue(objJson.data.ls_per_nrodocidentidad);

                            winlogeo.down('#ls_cta_password').setValue(objJson.data.ls_per_nrodocidentidad);

                            win.close();
                        }
                }
            },
            failure: function(form,action){

                var objJson =Ext.JSON.decode(action.response.responseText);

                Ext.MessageBox.alert('Mensaje',objJson.msgError);

            },
            params:{
                operacion:1,
                accion:ln_accion
            }

        });
    },

    onBtncerrarClick: function(button, e, eOpts) {
               button.up('window').close();
    },

    init: function(application) {
        this.control({
            "#winglbpersona #btnguardar": {
                click: this.onBtnguardarClick
            },
            "#winglbpersona #btncerrar": {
                click: this.onBtncerrarClick
            }
        });
    }

});
