/*
 * File: app/mundialito/view/gmo/gmu/persona/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.persona.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.persona.winMtto'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer'
    ],

    height: 184,
    itemId: 'winglbpersona',
    width: 570,
    layout: 'border',
    title: 'Registro de Participante',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Menu de opciones:'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnguardar',
                            iconCls: 'btnSave',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btncerrar',
                            iconCls: 'btnClose',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    itemId: 'frmglbpersona',
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/Mundialito/process/lst_glb_persona.php',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            itemId: 'ln_per_codigo',
                            width: 150,
                            fieldLabel: 'Label',
                            name: 'ln_per_codigo',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'accion',
                            width: 150,
                            fieldLabel: 'Label',
                            name: 'accion'
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'win_parent',
                            width: 150,
                            fieldLabel: 'Label',
                            name: 'win_parent'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'ls_per_nombre',
                            fieldLabel: 'Nombres',
                            name: 'ls_per_nombre',
                            fieldStyle: 'text-transform: uppercase;',
                            allowBlank: false,
                            emptyText: 'Ingresar Apellidos y Nombres'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'ln_tpo_codigo',
                            fieldLabel: 'Tipo Documento',
                            name: 'ln_tpo_codigo',
                            allowBlank: false,
                            emptyText: 'Seleccionar tipo de documento de identidad',
                            displayField: 'tpo_descripcion',
                            queryMode: 'local',
                            store: 'gmo.gmu.utiles.sttipodocidentidad',
                            valueField: 'tpo_codigo'
                        },
                        {
                            xtype: 'fieldcontainer',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'ls_per_nrodocidentidad',
                                    fieldLabel: 'Nro. Documento',
                                    name: 'ls_per_nrodocidentidad',
                                    allowBlank: false,
                                    emptyText: 'Numero de documento de identidad'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'ls_per_movil',
                                    margin: '0 0 0 10',
                                    fieldLabel: 'Nro. Movil',
                                    name: 'ls_per_movil'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'ln_pai_codigo',
                            fieldLabel: 'Region',
                            name: 'ln_pai_codigo',
                            allowBlank: false,
                            displayField: 'pai_denominacion',
                            queryMode: 'local',
                            store: 'gmo.gmu.utiles.stpais',
                            valueField: 'pai_codigo'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});