/*
 * File: app/mundialito/view/gmo/gmu/excelenciareg/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.excelenciareg.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.excelenciareg.winMtto'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.form.field.Trigger',
        'Ext.grid.plugin.CellEditing',
        'Ext.form.field.Hidden'
    ],

    height: 391,
    itemId: 'wingmuexcelenciareg',
    width: 932,
    layout: 'border',
    title: 'Mejores Jugadores Campeonato',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Menu de opciones:'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            iconCls: 'btnSave',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCerrar',
                            iconCls: 'btnClose',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    itemId: 'frmgmuexcelenciareg',
                    bodyPadding: 10,
                    url: '/library/Mundialito/process/lst_gmu_excelenciareg.php',
                    dockedItems: [
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            itemId: 'grdgmuexcelenciareg',
                            store: 'gmo.gmu.excelenciareg.stexcelenciareggrupo',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_exr_codigo',
                                    text: 'Ln Exr Codigo',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 466,
                                    dataIndex: 'ls_exc_descripcion',
                                    text: 'Descripcion'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_gru_codigo',
                                    text: 'Ln Gru Codigo',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'ls_gru_denominacion',
                                    text: 'Ls Gru Denominacion'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    width: 71,
                                    dataIndex: 'ln_jgd_codigo',
                                    text: 'Jugador',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 429,
                                    dataIndex: 'ls_jgd_nombre',
                                    text: 'Jugador',
                                    editor: {
                                        xtype: 'triggerfield',
                                        onTrigger1Click: function() {
                                            var component = this;

                                            var ln_trn_codigo = 1;

                                            var win = Ext.create ( 'mundialito.view.gmo.gmu.jugador.winListado' );

                                            win.down('#ln_trn_codigo').setValue(ln_trn_codigo);

                                            win.on( 'seleccionar', function ( personaCodigo, personaDesc ){
                                                var stMain = Ext.StoreManager.lookup ( 'gmo.gmu.excelenciareg.stexcelenciareggrupo' );
                                                if ( stMain === null ){
                                                    Ext.MessageBox.alert ( 'Error', 'No existe el store registrado' );
                                                    return ;
                                                }
                                                var record = stMain.getById ( component.keyId );
                                                record.set( 'ln_jgd_codigo', personaCodigo );
                                                record.set( 'ls_jgd_nombre', personaDesc );
                                            });

                                            win.show();
                                        },
                                        setKeyId: function(key) {
                                            this.keyId = key;
                                        },
                                        keyId: 'null',
                                        triggerCls: 'verJugador'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'ln_reg_codigo',
                                    text: 'ln_reg_codigo'
                                }
                            ],
                            plugins: [
                                Ext.create('Ext.grid.plugin.CellEditing', {
                                    clicksToEdit: 1,
                                    listeners: {
                                        beforeedit: {
                                            fn: me.onCellEditingBeforeEdit,
                                            scope: me
                                        }
                                    }
                                })
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_reg_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_reg_codigo'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_gru_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_gru_codigo'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_trn_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_trn_codigo'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'accion',
                            fieldLabel: 'Label',
                            name: 'accion'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onCellEditingBeforeEdit: function(editor, e, eOpts) {
           if ( e.field === 'ls_jgd_nombre' ){
                var trigger = e.column.field;
                    trigger.setKeyId ( e.record.get ( 'ln_exr_codigo' ) );
            }


    }

});