/*
 * File: app/mundialito/view/gmo/gmu/partidoreg/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.partidoreg.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.partidoreg.winMtto'
    ],
    requires: [
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.form.field.Number',
        'Ext.grid.plugin.CellEditing',
        'Ext.form.field.Hidden'
    ],

    height: 325,
    itemId: 'winmttopartidoreg',
    width: 629,
    layout: 'border',
    title: 'Registro de Partidos de Grupo',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    itemId: 'frmgmupartidoreg',
                    bodyPadding: 10,
                    url: '/library/Mundialito/process/lst_gmu_partidoreg.php',
                    dockedItems: [
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            itemId: 'grdgmupartidoreg',
                            store: 'gmo.gmu.partidoreg.stpartidoreggrupo',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'Menu de opciones:'
                                        },
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btnguardar',
                                            iconCls: 'btnSave',
                                            text: 'Guardar'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'btncerrar',
                                            iconCls: 'btnClose',
                                            text: 'Cerrar'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        }
                                    ]
                                }
                            ],
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_prn_codigo',
                                    text: 'Ln Prn Codigo',
                                    format: '00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_reg_codigo',
                                    text: 'Ln Reg Codigo',
                                    format: '00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_prd_codigo',
                                    text: 'Ln Prd Codigo',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 66,
                                    dataIndex: 'ls_gru_denominacion',
                                    text: 'Grupo'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_prd_numero',
                                    text: 'Ln Prd Numero',
                                    format: '00'
                                },
                                {
                                    xtype: 'datecolumn',
                                    hidden: true,
                                    dataIndex: 'ld_prd_fecha',
                                    text: 'Ld Prd Fecha',
                                    format: 'm/j/Y'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_equ_local',
                                    text: 'Ln Equ Local',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 157,
                                    dataIndex: 'ls_equ_local_des',
                                    text: 'Equipo 1'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    align: 'center',
                                    dataIndex: 'ln_equ_gollocal',
                                    text: 'Goles',
                                    format: '00',
                                    editor: {
                                        xtype: 'numberfield',
                                        minValue: 0
                                    }
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_equ_visitante',
                                    text: 'Ln Equ Visitante',
                                    format: '00'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 169,
                                    dataIndex: 'ls_equ_visitante_des',
                                    text: 'Equipo 2'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    align: 'center',
                                    dataIndex: 'ln_equ_golvisita',
                                    text: 'Goles',
                                    format: '00',
                                    editor: {
                                        xtype: 'numberfield',
                                        minValue: 0
                                    }
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_gru_tipo',
                                    text: 'Ln Gru Tipo',
                                    format: '00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'ln_gru_codigo',
                                    text: 'Ln Gru Codigo',
                                    format: '00'
                                }
                            ],
                            plugins: [
                                Ext.create('Ext.grid.plugin.CellEditing', {
                                    pluginId: 'editor',
                                    clicksToEdit: 1
                                })
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_reg_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_reg_codigo'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_gru_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_gru_codigo'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_nro_tab',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'accion',
                            fieldLabel: 'Label',
                            name: 'accion'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});