/*
 * File: app/mundialito/controller/gmo/gmu/registro/ctrMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.controller.gmo.gmu.registro.ctrMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gmu.registro.ctrMtto'
    ],

    views: [
        'gmo.gmu.registro.winMtto'
    ],

    refs: [
        {
            ref: 'Mtto',
            selector: '#wingmuregistro'
        },
        {
            ref: 'Main',
            selector: '#vpngmumain'
        }
    ],

    onBtnGuardarClick: function(button, e, eOpts) {
                var me = this,
                    win = me.getMtto(),
                    vp = me.getMain(),
                    ln_accion = win.down('#accion'),
                    frm = win.down('#frmgmuregistro');

                    if (frm.isValid()===false){

                        Ext.MessageBox.alert('Mensaje','Datos de formulario de registro incompleto');

                        return;
                    }


          frm.submit({
            success: function(form, action){

                var objJson =Ext.JSON.decode(action.response.responseText);
                if (objJson.success){
                    Ext.MessageBox.alert('Mensaje',objJson.msg);
                    vp.down('#grdgmuregistro').getStore().reload();
                    vp.down('#grdgmuregistro').getSelectionModel().deselectAll();
                    win.close();
                }
            },
            failure: function(form,action){

                var objJson =Ext.JSON.decode(action.response.responseText);

                Ext.MessageBox.alert('Mensaje',objJson.msgError);

            },
            params:{
                operacion:1,
                accion:ln_accion.getValue()
            }

        });

    },

    onBtnCerrarClick: function(button, e, eOpts) {
                    button.up('window').close();
    },

    init: function(application) {
        this.control({
            "#wingmuregistro #btnGuardar": {
                click: this.onBtnGuardarClick
            },
            "#wingmuregistro #btnCerrar": {
                click: this.onBtnCerrarClick
            }
        });
    }

});
