/*
 * File: app/mundialito/controller/gmo/gmu/registro/ctrMain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.controller.gmo.gmu.registro.ctrMain', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gmu.registro.ctrMain'
    ],

    refs: [
        {
            ref: 'Main',
            selector: '#vpngmumain'
        }
    ],

    onBtnrecuperarClick: function(button, e, eOpts) {
                var me = this,

                    vp = me.getMain(),

                    ln_per_codigo=vp.down('#ln_per_codigo').getValue(),

                    st_registro = vp.down('#grdgmuregistro').getStore();

                    st_registro.load({
                        params:{
                            'operacion':2,
                            'ln_per_codigo':ln_per_codigo
                        }
                    });
    },

    onBtnretrievegrupoClick: function(button, e, eOpts) {
                    var me = this,
                        vp = me.getMain(),
                        grd = vp.down('#grdgmuregistro'),
                        sm = grd.getSelectionModel(),
                        st_grupodet = vp.down('#grdgmugrupodetreg').getStore();

                        if (sm.hasSelection()===false){
                            return;
                        }

                        var rec = sm.getSelection()[0];

                        st_grupodet.load({
                            params:{
                                'operacion':2,
                                'ln_reg_codigo':rec.data.ln_reg_codigo
                            }
                        });


    },

    onGrdgmuregistroSelectionChange: function(model, selected, eOpts) {
                var me = this,
                    vp = me.getMain(),
                    btn_retrievegrupo =vp.down('#btnretrievegrupo'),
                    btn_octavo = vp.down('#btnretrieveoctavo'),
                    btn_cuarto = vp.down('#btnretrievecuarto'),
                    btn_final = vp.down('#btnretrievefinal'),
                    btn_adici = vp.down('#btnretrieveadicionalreg'),
                    btn_exce  = vp.down('#btnretrieveexcelenciareg');
                    btn_rst	  = vp.down('#btnRetrieveResultado');


                    me.onBtnretrievegrupoClick(me,me.btn_retrievegrupo);
                    me.onBtnretrieveoctavoClick(me,me.btn_octavo);
                    me.onBtnretrievecuartoClick(me,me.btn_cuarto);
                    me.onBtnretrievefinalClick(me,me.btn_final);
                    me.onBtnretrieveadicionalregClick(me,me.btn_adici);
                    me.onBtnretrieveexcelenciaregClick(me,me.btn_exce);
                    me.onBtnRetrieveResultadoClick(me,me.btn_rst);




    },

    onBtnretrieveoctavoClick: function(button, e, eOpts) {
                   var me = this,
                                vp = me.getMain(),
                                grd = vp.down('#grdgmuregistro'),
                                sm = grd.getSelectionModel(),
                                st_grupodet = vp.down('#grdgmupartidooctavo').getStore();

                                if (sm.hasSelection()===false){
                                    return;
                                }

                                var rec = sm.getSelection()[0];

                                st_grupodet.load({
                                    params:{
                                        'operacion':2,
                                        'ln_reg_codigo':rec.data.ln_reg_codigo,
                                        'ln_gru_codigo':9,
                                        'ls_condicion':'T'
                                    }
                                });

    },

    onBtnretrievecuartoClick: function(button, e, eOpts) {
           var me = this,
                                vp = me.getMain(),
                                grd = vp.down('#grdgmuregistro'),
                                sm = grd.getSelectionModel(),
                                st_grupodet = vp.down('#grdgmupartidocuarto').getStore();

                                if (sm.hasSelection()===false){
                                    return;
                                }

                                var rec = sm.getSelection()[0];

                                st_grupodet.load({
                                    params:{
                                        'operacion':2,
                                        'ln_reg_codigo':rec.data.ln_reg_codigo,
                                        'ln_gru_codigo':10,
                                        'ls_condicion':'T'
                                    }
                                });

    },

    onBtnretrievefinalClick: function(button, e, eOpts) {
           var me = this,
                                vp = me.getMain(),
                                grd = vp.down('#grdgmuregistro'),
                                sm = grd.getSelectionModel(),
                                st_grupodet = vp.down('#grdgmupartidofinal').getStore();

                                if (sm.hasSelection()===false){
                                    return;
                                }

                                var rec = sm.getSelection()[0];

                                st_grupodet.load({
                                    params:{
                                        'operacion':2,
                                        'ln_reg_codigo':rec.data.ln_reg_codigo,
                                        'ln_gru_codigo':11,
                                        'ls_condicion':'T'
                                    }
                                });

    },

    onBtnmodificaroctavoClick: function(button, e, eOpts) {
            var me =this,
                vp=me.getMain(),
                grd=vp.down('#grdgmupartidooctavo'),
                sm=grd.getSelectionModel();

                if(sm.hasSelection()===false){

                    Ext.MessageBox.alert('Mensaje','Seleccione grupo del cual desea modificar los valores');

                    return;
                }

                var win=Ext.create('gmo.gmu.partidoreg.winMtto'),

                    rec = sm.getSelection()[0];

                win.down('#ln_reg_codigo').setValue(rec.data.ln_reg_codigo);

                win.down('#ln_gru_codigo').setValue(rec.data.ln_gru_codigo);

                win.down('#accion').setValue(2);

                win.down('#ln_nro_tab').setValue(1);

                win.show();
    },

    onBtnmodificarcuartoClick: function(button, e, eOpts) {
          var me =this,
                vp=me.getMain(),
                grd=vp.down('#grdgmupartidocuarto'),
                sm=grd.getSelectionModel();

                if(sm.hasSelection()===false){

                    Ext.MessageBox.alert('Mensaje','Seleccione grupo del cual desea modificar los valores');

                    return;
                }

                var win=Ext.create('gmo.gmu.partidoreg.winMtto'),

                    rec = sm.getSelection()[0];

                win.down('#ln_reg_codigo').setValue(rec.data.ln_reg_codigo);

                win.down('#ln_gru_codigo').setValue(rec.data.ln_gru_codigo);

                win.down('#accion').setValue(2);

                win.down('#ln_nro_tab').setValue(2);

                win.show();
    },

    onBtnmodificarfinalClick: function(button, e, eOpts) {
            var me =this,
                vp=me.getMain(),
                grd=vp.down('#grdgmupartidofinal'),
                sm=grd.getSelectionModel();

                if(sm.hasSelection()===false){

                    Ext.MessageBox.alert('Mensaje','Seleccione grupo del cual desea modificar los valores');

                    return;
                }

                var win=Ext.create('gmo.gmu.partidoreg.winMtto'),

                    rec = sm.getSelection()[0];

                win.down('#ln_reg_codigo').setValue(rec.data.ln_reg_codigo);

                win.down('#ln_gru_codigo').setValue(rec.data.ln_gru_codigo);

                win.down('#accion').setValue(2);

                win.down('#ln_nro_tab').setValue(3);

                win.show();
    },

    onBtnnuevoregistroClick: function(button, e, eOpts) {

                var me = this,
                    vp = me.getMain(),
                    ln_per_codigo = vp.down('#ln_per_codigo').getValue(),
                    ls_per_nombre = vp.down('#ls_per_nombre').getValue(),
                    st_registro = vp.down('#grdgmuregistro').getStore(),

                    win = Ext.create('mundialito.view.gmo.gmu.registro.winMtto');

                    win.down('#ln_per_codigo').setValue(ln_per_codigo);

                    win.down('#ls_per_nombre').setValue(ls_per_nombre);

                    win.down('#accion').setValue(1);

                    win.show();

    },

    onBtnanularregistroClick: function(button, e, eOpts) {
                var me = this,
                    vp = me.getMain(),
                    grd = vp.down('#grdgmuregistro'),
                    sm=grd.getSelectionModel();

                    if (sm.hasSelection()===false){

                        Ext.MessageBox.alert('Mensaje','Debe seleccionar registro que desea anular');

                        return;
                    }

                    var rec=sm.getSelection()[0];

                    var ln_reg_codigo = rec.data.ln_reg_codigo;

                    var ls_url = '/library/Mundialito/process/lst_gmu_registro.php';

                    var ls_params={
                        'operacion':1,
                        'accion':3,
                        'ln_reg_codigo':ln_reg_codigo,
                        'ln_per_codigo':0
                    };

                    Ext.MessageBox.confirm('Mensaje','Desea anular registro seleccionado',function(rsp){

                    if(rsp==='yes'){

                         me.getController('gmo.gmu.utiles.ctrfuncion').fn_AjaxRequest(ls_params,ls_url,function(val){

                           if(val){

                               grd.getStore().remove(rec);

                               Ext.Msg.alert('Mensaje','Anulacion de registro realizado correctamente');
                           }

                         });

                    }

                });



    },

    onBtnmodificarClick: function(button, e, eOpts) {
            var me =this,
                vp=me.getMain(),
                grd=vp.down('#grdgmugrupodetreg'),
                sm=grd.getSelectionModel();

                if(sm.hasSelection()===false){

                    Ext.MessageBox.alert('Mensaje','Seleccione grupo del cual desea modificar los valores');

                    return;
                }

                var win=Ext.create('gmo.gmu.partidoreg.winMtto'),

                    rec = sm.getSelection()[0];

                win.down('#ln_reg_codigo').setValue(rec.data.ln_reg_codigo);

                win.down('#ln_gru_codigo').setValue(rec.data.ln_gru_codigo);

                win.down('#accion').setValue(2);

                win.down('#ln_nro_tab').setValue(0);

                win.show();
    },

    onBtnretrieveadicionalregClick: function(button, e, eOpts) {
            var me = this,
                vp = me.getMain(),
                grd = vp.down('#grdgmuregistro'),
                sm = grd.getSelectionModel(),
                st_grupodet = vp.down('#grdgmuadicionalreg').getStore();

                if (sm.hasSelection()===false){
                        return;
                }

                var rec = sm.getSelection()[0];

                st_grupodet.load({
                  params:{
                    'operacion':2,
                    'ln_reg_codigo':rec.data.ln_reg_codigo,
                    'ln_gru_codigo':14
                   }
                });

    },

    onBtnmodificaradicionalregClick: function(button, e, eOpts) {

        var me =this,
            vp=me.getMain(),
            grd=vp.down('#grdgmuadicionalreg'),
            sm=grd.getSelectionModel();

        if(sm.hasSelection()===false){

            Ext.MessageBox.alert('Mensaje','Seleccione registro que desea modificar');

            return;
        }

        var win=Ext.create('gmo.gmu.adicionalreg.winMtto'),

            rec = sm.getSelection()[0];

        win.down('#ln_reg_codigo').setValue(rec.data.ln_reg_codigo);

        win.down('#ln_gru_codigo').setValue(rec.data.ln_gru_codigo);

        win.down('#accion').setValue(2);

        win.show();
    },

    onBtnretrieveexcelenciaregClick: function(button, e, eOpts) {
            var me = this,
                vp = me.getMain(),
                grd = vp.down('#grdgmuregistro'),
                sm = grd.getSelectionModel(),
                st_grupodet = vp.down('#grdgmuexcelenciareg').getStore();

                if (sm.hasSelection()===false){
                        return;
                }

                var rec = sm.getSelection()[0];

                st_grupodet.load({
                  params:{
                    'operacion':2,
                    'ln_reg_codigo':rec.data.ln_reg_codigo,
                    'ln_gru_codigo':15
                   }
                });

    },

    onBtnmodificarexcelenciaregClick: function(button, e, eOpts) {
        var me =this,
            vp=me.getMain(),
            grd=vp.down('#grdgmuexcelenciareg'),
            sm=grd.getSelectionModel();

        if(sm.hasSelection()===false){

            Ext.MessageBox.alert('Mensaje','Seleccione registro que desea modificar');

            return;
        }

        var win=Ext.create('gmo.gmu.excelenciareg.winMtto'),

            rec = sm.getSelection()[0];

        win.down('#ln_reg_codigo').setValue(rec.data.ln_reg_codigo);

        win.down('#ln_gru_codigo').setValue(rec.data.ln_gru_codigo);

        win.down('#ln_trn_codigo').setValue(1);

        win.down('#accion').setValue(2);

        win.show();
    },

    onBtnCambioPasswordClick: function(button, e, eOpts) {
            var me =this,
                vp = me.getMain(),
                ln_per_codigo = vp.down('#ln_per_codigo').getValue();

            var win = Ext.create('gmo.gmu.security.winchangepwd');

                win.down('#ln_per_codigo').setValue(ln_per_codigo);

                win.show();
    },

    onBtnactualizapersonaClick: function(button, e, eOpts) {
                var me= this,

                    vp = me.getMain(),

                    ln_per_codigo = vp.down('#ln_per_codigo').getValue();

                    if (ln_per_codigo===undefined) { return;}

                var win = Ext.create('gmo.gmu.persona.winMtto'),
                    st_persona = Ext.create('gmo.gmu.persona.stpersona');

                    st_persona.load({
                        params:{
                            'operacion':2,
                            'ln_per_codigo':ln_per_codigo
                        },
                        callback:function(records,options,success){
                            if(success&&records[0]!==undefined){
                                win.down('#frmglbpersona').loadRecord(records[0]);
                                win.down('#accion').setValue(2);
                                win.down('#win_parent').setValue(1);
                                win.show();
                            }
                        }

                    });

    },

    onVpngmumainAfterLayout: function(container, layout, eOpts) {
            var me = this,

                        vp=me.getMain(),

                        btn_resumen = vp.down('#btnRetrieveResumen'),

                        btn_retrieve = vp.down('#btnrecuperar');

                        me.onBtnrecuperarClick(me,me.btn_retrieve);

                        me.onBtnRetrieveResumenClick(me,me.btn_resumen);

    },

    onBtnCerrarSesionClick: function(button, e, eOpts) {
               var me = this,

                    vp = me.getMain();

                    Ext.MessageBox.confirm('Mensaje','Desea cerrar sesion',function(rsp){

                    if(rsp!=='yes'){return;}

                      vp.close();


                  });
    },

    onBtnRetrieveResultadoClick: function(button, e, eOpts) {
                        var me = this,
                        vp = me.getMain(),
                        grd = vp.down('#grdgmuregistro'),
                        sm = grd.getSelectionModel(),
                        st_rst = vp.down('#grdgmuresultado').getStore();

                        if (sm.hasSelection()===false){
                                return;
                        }

                        var rec = sm.getSelection()[0];

                        st_rst.load({
                          params:{
                            'operacion':3,
                            'ln_reg_codigo':rec.data.ln_reg_codigo
                           }
                        });



    },

    onBtnexportarClick: function(button, e, eOpts) {
            var me = this,
                vp = me.getMain(),
                grd = vp.down('#grdgmuregistro'),
                sm = grd.getSelectionModel(),
                frm = vp.down('#frmgmuexportar');


                if (sm.hasSelection()===false){
                    return;
                }

                var rec =sm.getSelection()[0];

                frm.getForm().submit({
                    standardSubmit:true,
                    url:'/library/Mundialito/process/lst_gmu_exportexcel.php',
                    headers:{

                    },
                    method: 'POST',
                    params:{
                        'operacion':1,
                        'ln_reg_codigo':rec.data.ln_reg_codigo
                    }

                });

    },

    onBtnRetrieveResumenClick: function(button, e, eOpts) {
                var me = this,

                    vp = me.getMain(),

                    st_resumen = vp.down('#grdgmuresumen').getStore();

                    st_resumen.load({
                        params:{
                            'operacion':1,
                            'ln_trn_codigo':1
                        }
                    });

    },

    init: function(application) {
        this.control({
            "#vpngmumain #btnrecuperar": {
                click: this.onBtnrecuperarClick
            },
            "#vpngmumain #btnretrievegrupo": {
                click: this.onBtnretrievegrupoClick
            },
            "#vpngmumain #grdgmuregistro": {
                selectionchange: this.onGrdgmuregistroSelectionChange
            },
            "#vpngmumain #btnretrieveoctavo": {
                click: this.onBtnretrieveoctavoClick
            },
            "#vpngmumain  #btnretrievecuarto": {
                click: this.onBtnretrievecuartoClick
            },
            "#vpngmumain  #btnretrievefinal": {
                click: this.onBtnretrievefinalClick
            },
            "#vpngmumain  #btnmodificaroctavo": {
                click: this.onBtnmodificaroctavoClick
            },
            "#vpngmumain #btnmodificarcuarto": {
                click: this.onBtnmodificarcuartoClick
            },
            "#vpngmumain #btnmodificarfinal": {
                click: this.onBtnmodificarfinalClick
            },
            "#vpngmumain #btnnuevoregistro": {
                click: this.onBtnnuevoregistroClick
            },
            "#vpngmumain #btnanularregistro": {
                click: this.onBtnanularregistroClick
            },
            "#vpngmumain #btnmodificar": {
                click: this.onBtnmodificarClick
            },
            "#vpngmumain #btnretrieveadicionalreg": {
                click: this.onBtnretrieveadicionalregClick
            },
            "#vpngmumain #btnmodificaradicionalreg": {
                click: this.onBtnmodificaradicionalregClick
            },
            "#vpngmumain #btnretrieveexcelenciareg": {
                click: this.onBtnretrieveexcelenciaregClick
            },
            "#vpngmumain #btnmodificarexcelenciareg": {
                click: this.onBtnmodificarexcelenciaregClick
            },
            "#vpngmumain #btnCambioPassword": {
                click: this.onBtnCambioPasswordClick
            },
            "#vpngmumain  #btnactualizapersona": {
                click: this.onBtnactualizapersonaClick
            },
            "#vpngmumain": {
                afterlayout: this.onVpngmumainAfterLayout
            },
            "#vpngmumain #btnCerrarSesion": {
                click: this.onBtnCerrarSesionClick
            },
            "#vpngmumain  #btnRetrieveResultado": {
                click: this.onBtnRetrieveResultadoClick
            },
            "#vpngmumain  #btnexportar": {
                click: this.onBtnexportarClick
            },
            "#vpngmumain #btnRetrieveResumen": {
                click: this.onBtnRetrieveResumenClick
            }
        });
    }

});
