/*
 * File: app/mundialito/model/gmo/gmu/grupodetreg/mdgrupodetreg.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.model.gmo.gmu.grupodetreg.mdgrupodetreg', {
    extend: 'Ext.data.Model',

    alternateClassName: [
        'gmo.gmu.grupodetreg.mdgrupodetreg'
    ],
    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ln_rgd_codigo',

    fields: [
        {
            name: 'ln_rgd_codigo',
            type: 'int'
        },
        {
            name: 'ln_reg_codigo',
            type: 'int'
        },
        {
            name: 'ln_gru_codigo',
            type: 'int'
        },
        {
            name: 'ls_gru_denominacion',
            type: 'string'
        },
        {
            name: 'ls_equ_denominacion',
            type: 'string'
        },
        {
            name: 'ln_eqd_puntos',
            type: 'int'
        },
        {
            name: 'ln_eqd_ganado',
            type: 'int'
        },
        {
            name: 'ln_eqd_empatado',
            type: 'int'
        },
        {
            name: 'ln_eqd_perdido',
            type: 'int'
        },
        {
            name: 'ln_eqd_golfavor',
            type: 'int'
        },
        {
            name: 'ln_eqd_golcontra',
            type: 'int'
        },
        {
            name: 'ln_eqd_puesto',
            type: 'int'
        },
        {
            name: 'ln_eqd_diferencia',
            type: 'int'
        }
    ]
});