/*
 * File: app/mundialito/view/gmo/gmu/jugador/winListado.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.jugador.winListado', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.jugador.winListado'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.field.Hidden',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number'
    ],

    height: 341,
    itemId: 'wingmujugadorlistado',
    width: 595,
    layout: 'border',
    title: 'Listado de Jugadores',
    modal: true,

    initComponent: function() {
        var me = this;

        me.addEvents(
            'seleccionar'
        );

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'txtcriterio',
                            width: 256,
                            fieldLabel: 'Nombre o Pais',
                            name: 'txtcriterio'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnRecuperar',
                            iconCls: 'btnRetrieve',
                            text: 'Recuperar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSeleccionar',
                            iconCls: 'btnSelect',
                            text: 'Seleccionar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCerrar',
                            iconCls: 'btnClose',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'hiddenfield',
                            itemId: 'ln_trn_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_trn_codigo'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    itemId: 'grdgmujugador',
                    store: 'gmo.gmu.jugador.stjugador',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'ln_jgd_codigo',
                            text: 'Ln Jgd Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 576,
                            dataIndex: 'ls_jgd_nombre',
                            text: 'Nombres'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'ln_trn_codigo',
                            text: 'Ln Trn Codigo',
                            format: '00'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});