/*
 * File: app/mundialito/model/gmo/gmu/partidoreg/mdpartidoreg.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.model.gmo.gmu.partidoreg.mdpartidoreg', {
    extend: 'Ext.data.Model',

    alternateClassName: [
        'gmo.gmu.partidoreg.mdpartidoreg'
    ],
    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ln_prn_codigo',

    fields: [
        {
            name: 'ln_prn_codigo',
            type: 'int'
        },
        {
            name: 'ln_reg_codigo',
            type: 'int'
        },
        {
            name: 'ln_prd_codigo',
            type: 'int'
        },
        {
            name: 'ls_gru_denominacion',
            type: 'string'
        },
        {
            name: 'ln_prd_numero',
            type: 'int'
        },
        {
            name: 'ld_prd_fecha',
            type: 'date'
        },
        {
            name: 'ln_equ_local',
            type: 'int'
        },
        {
            name: 'ls_equ_local_des',
            type: 'string'
        },
        {
            name: 'ln_equ_visitante',
            type: 'int'
        },
        {
            name: 'ls_equ_visitante_des',
            type: 'string'
        },
        {
            name: 'ln_equ_gollocal',
            type: 'int'
        },
        {
            name: 'ln_equ_golvisita',
            type: 'int'
        },
        {
            name: 'ln_gru_tipo',
            type: 'int'
        },
        {
            name: 'ln_gru_codigo',
            type: 'int'
        }
    ]
});