/*
 * File: app/mundialito/model/gmo/gmu/adicionalreg/mdadicionalreg.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.model.gmo.gmu.adicionalreg.mdadicionalreg', {
    extend: 'Ext.data.Model',

    alternateClassName: [
        'gmo.gmu.adicionalreg.mdadicionalreg'
    ],
    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'ln_adr_codigo',

    fields: [
        {
            name: 'ln_adr_codigo',
            type: 'int'
        },
        {
            name: 'ln_reg_codigo',
            type: 'int'
        },
        {
            name: 'ln_gru_codigo',
            type: 'int'
        },
        {
            name: 'ls_gru_denominacion',
            type: 'string'
        },
        {
            name: 'ls_adc_descripcion',
            type: 'string'
        },
        {
            name: 'ln_adr_cantidad',
            type: 'int'
        }
    ]
});