/*
 * File: app/mundialito/view/gmo/gmu/registro/vpmain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.registro.vpmain', {
    extend: 'Ext.container.Viewport',

    alternateClassName: [
        'gmo.gmu.registro.vpmain'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Hidden',
        'Ext.form.field.Display',
        'Ext.toolbar.Spacer',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.grid.Panel',
        'Ext.form.Label',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate',
        'Ext.grid.RowNumberer',
        'Ext.form.Panel'
    ],

    itemId: 'vpngmumain',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    region: 'north',
                    itemId: 'mytoolbar5',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            itemId: 'ln_per_codigo',
                            name: 'ln_per_codigo'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'ls_per_nombre',
                            fieldLabel: 'Participante',
                            labelWidth: 70,
                            name: 'ls_per_nombre'
                        },
                        {
                            xtype: 'tbspacer'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnactualizapersona',
                            iconCls: 'btnEdit',
                            text: 'Actualizar Datos'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCambioPassword',
                            iconCls: 'btnSesion',
                            text: 'Cambio Password'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCerrarSesion',
                            iconCls: 'btnClose',
                            text: 'Cerrar Session'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'north',
                    height: 150,
                    itemId: 'grdgmuregistro',
                    store: 'gmo.gmu.registro.stregistro',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Menu de opciones:'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnrecuperar',
                                    iconCls: 'btnRetrieve',
                                    text: 'Recuperar'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnnuevoregistro',
                                    iconCls: 'btnNew',
                                    text: 'Nuevo'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnanularregistro',
                                    iconCls: 'btnDelete',
                                    text: 'Anular'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnexportar',
                                    iconCls: 'btnExcel',
                                    text: 'Exportar'
                                }
                            ]
                        }
                    ],
                    viewConfig: {
                        itemId: 'mygridview'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            align: 'right',
                            dataIndex: 'ln_reg_codigo',
                            text: 'Ln Reg Codigo',
                            format: '00'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 63,
                            dataIndex: 'ln_reg_numero',
                            text: 'Nro.',
                            format: '00'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'ld_reg_fecha',
                            text: 'Fecha'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 343,
                            dataIndex: 'ls_per_nombre',
                            text: 'Nombres'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 139,
                            dataIndex: 'ls_per_nrodocidentidad',
                            text: 'DNI'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 302,
                            dataIndex: 'ls_trn_denominacion',
                            text: 'Torneo'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'ld_trn_fechai',
                            text: 'Fecha Inicio'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'ld_trn_fechat',
                            text: 'Fecha Termino'
                        },
                        {
                            xtype: 'datecolumn',
                            hidden: true,
                            dataIndex: 'ln_reg_estado',
                            text: 'ln_reg_estado'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 113,
                            align: 'center',
                            dataIndex: 'ls_reg_estado',
                            text: 'Estado'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmugrupo',
                            layout: 'border',
                            title: 'Grupos',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmugrupodetreg',
                                    store: 'gmo.gmu.grupodetreg.stgrupodetreg',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretrievegrupo',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnmodificar',
                                                    iconCls: 'btnEdit',
                                                    text: 'Modificar'
                                                }
                                            ]
                                        }
                                    ],
                                    viewConfig: {
                                        getRowClass: function(record, rowIndex, rowParams, store) {
                                            switch ( record.get ( 'ln_eqd_puesto' ) ) {
                                                case 1: //Clasificado
                                                return 'clsClasificado';
                                                case 2: //Clasificado
                                                return 'clsClasificado';
                                                default ://No Clasificado
                                                return '';
                                            }
                                        },
                                        itemId: 'gvgmugrupodetreg'
                                    },
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_rgd_codigo',
                                            text: 'Ln Rgd Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'Ln Reg Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'Ln Gru Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Grupo'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ls_equ_denominacion',
                                            text: 'Equipo'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_puntos',
                                            text: 'PTO',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_ganado',
                                            text: 'P.G.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_empatado',
                                            text: 'P.E.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_perdido',
                                            text: 'P.P.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_golfavor',
                                            text: 'G.F.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_golcontra',
                                            text: 'G.C.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_eqd_puesto',
                                            text: 'Ln Eqd Puesto',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_eqd_diferencia',
                                            text: 'DIF.',
                                            format: '00'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmuoctavo',
                            layout: 'border',
                            title: 'Octavos',
                            tabConfig: {
                                xtype: 'tab',
                                itemId: 'pnltabgmuoctavo'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmupartidooctavo',
                                    store: 'gmo.gmu.partidoreg.stpartidoreg',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretrieveoctavo',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnmodificaroctavo',
                                                    iconCls: 'btnEdit',
                                                    text: 'Modificar'
                                                }
                                            ]
                                        }
                                    ],
                                    viewConfig: {
                                        itemId: 'gvgmupartidooctavo'
                                    },
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prn_codigo',
                                            text: 'Ln Prn Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'Ln Reg Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prd_codigo',
                                            text: 'Ln Prd Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Ls Gru Denominacion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'ln_prd_numero',
                                            text: 'Nro.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            hidden: true,
                                            dataIndex: 'ld_prd_fecha',
                                            text: 'Ld Prd Fecha',
                                            format: 'm/j/Y'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_equ_local',
                                            text: 'Ln Equ Local',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (record.get('ln_equ_gollocal')>record.get('ln_equ_golvisita')) {return '<span style="color:blue;">'+record.get('ls_equ_local_des')+'</span>'; }
                                                else {return '<span>'+record.get('ls_equ_local_des')+'</span>';}
                                            },
                                            width: 300,
                                            dataIndex: 'ls_equ_local_des',
                                            text: 'Equipo 1'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_equ_gollocal',
                                            text: 'Goles',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_equ_visitante',
                                            text: 'Ln Equ Visitante',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (record.get('ln_equ_golvisita')>record.get('ln_equ_gollocal')) {return '<span style="color:blue;">'+record.get('ls_equ_visitante_des')+'</span>'; }
                                                else {return '<span>'+record.get('ls_equ_visitante_des')+'</span>';}
                                            },
                                            width: 300,
                                            dataIndex: 'ls_equ_visitante_des',
                                            text: 'Equipo 2'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_equ_golvisita',
                                            text: 'Goles',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'Ln Gru Tipo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'ln_gru_codigo',
                                            format: '00'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmucuarto',
                            layout: 'border',
                            title: 'Cuartos',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmupartidocuarto',
                                    store: 'gmo.gmu.partidoreg.stpartidoregcuarto',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretrievecuarto',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnmodificarcuarto',
                                                    iconCls: 'btnEdit',
                                                    text: 'Modificar'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prn_codigo',
                                            text: 'Ln Prn Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'Ln Reg Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prd_codigo',
                                            text: 'Ln Prd Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Ls Gru Denominacion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 53,
                                            dataIndex: 'ln_prd_numero',
                                            text: 'Nro.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            hidden: true,
                                            dataIndex: 'ld_prd_fecha',
                                            text: 'Ld Prd Fecha',
                                            format: 'm/j/Y'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_equ_local',
                                            text: 'Ln Equ Local',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (record.get('ln_equ_gollocal')>record.get('ln_equ_golvisita')) {return '<span style="color:blue;">'+record.get('ls_equ_local_des')+'</span>'; }
                                                else {return '<span>'+record.get('ls_equ_local_des')+'</span>';}

                                            },
                                            width: 300,
                                            dataIndex: 'ls_equ_local_des',
                                            text: 'Equipo 1'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_equ_gollocal',
                                            text: 'Goles',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_equ_visitante',
                                            text: 'Ln Equ Visitante',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (record.get('ln_equ_golvisita')>record.get('ln_equ_gollocal')) {return '<span style="color:blue;">'+record.get('ls_equ_visitante_des')+'</span>'; }
                                                else {return '<span>'+record.get('ls_equ_visitante_des')+'</span>';}
                                            },
                                            width: 300,
                                            dataIndex: 'ls_equ_visitante_des',
                                            text: 'Equipo 2'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_equ_golvisita',
                                            text: 'Goles',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_tipo',
                                            text: 'Ln Gru Tipo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'ln_gru_codigo',
                                            format: '00'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmufinal',
                            layout: 'border',
                            title: 'Final',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmupartidofinal',
                                    store: 'gmo.gmu.partidoreg.stpartidoregfinal',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretrievefinal',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnmodificarfinal',
                                                    iconCls: 'btnEdit',
                                                    text: 'Modificar'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prn_codigo',
                                            text: 'Ln Prn Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'Ln Reg Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prd_codigo',
                                            text: 'Ln Prd Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Ls Gru Denominacion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 61,
                                            dataIndex: 'ln_prd_numero',
                                            text: 'Nro.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            hidden: true,
                                            dataIndex: 'ld_prd_fecha',
                                            text: 'Ld Prd Fecha',
                                            format: 'm/j/Y'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_equ_local',
                                            text: 'Ln Equ Local',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (record.get('ln_equ_gollocal')>record.get('ln_equ_golvisita')) {
                                                    if (record.get('ln_gru_codigo')===13){
                                                    return  '<span style="color:blue; font-size:24px; font-weight: bold;  !important;">'+record.get('ls_equ_local_des')+'</span>';}
                                                    else{
                                                    return '<span style="color:blue;">'+record.get('ls_equ_local_des')+'</span>'; }
                                                }
                                                else {return '<span>'+record.get('ls_equ_local_des')+'</span>';}

                                            },
                                            width: 300,
                                            dataIndex: 'ls_equ_local_des',
                                            text: 'Equipo 1'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_equ_gollocal',
                                            text: 'Goles',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_equ_visitante',
                                            text: 'Ln Equ Visitante',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                if (record.get('ln_equ_golvisita')>record.get('ln_equ_gollocal')) {
                                                    if (record.get('ln_gru_codigo')===13){
                                                    return  '<span style="color:blue; font-size:24px; font-weight: bold;  !important;">'+record.get('ls_equ_visitante_des')+'</span>';}
                                                    else{
                                                    return '<span style="color:blue;">'+record.get('ls_equ_visitante_des')+'</span>'; }
                                                }
                                                else {return '<span>'+record.get('ls_equ_visitante_des')+'</span>';}
                                            },
                                            width: 300,
                                            dataIndex: 'ls_equ_visitante_des',
                                            text: 'Equipo 2'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'ln_equ_golvisita',
                                            text: 'Goles',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_tipo',
                                            text: 'Ln Gru Tipo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'ln_gru_codigo',
                                            format: '00'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmugol',
                            layout: 'border',
                            title: 'Goles  y Tarjetas',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmuadicionalreg',
                                    store: 'gmo.gmu.adicionalreg.stadicionalreg',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretrieveadicionalreg',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnmodificaradicionalreg',
                                                    iconCls: 'btnEdit',
                                                    text: 'Modificar'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            width: 73,
                                            align: 'center',
                                            dataIndex: 'ln_adr_codigo',
                                            text: 'Nro.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'Ln Reg Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'Ln Gru Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Ls Gru Denominacion'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 575,
                                            dataIndex: 'ls_adc_descripcion',
                                            text: 'Descripcion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_adr_cantidad',
                                            text: 'Cantidad',
                                            format: '00'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmumejor',
                            layout: 'border',
                            title: 'Goleador y Mejores Jugadores',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmuexcelenciareg',
                                    store: 'gmo.gmu.excelenciareg.stexcelenciareg',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnretrieveexcelenciareg',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnmodificarexcelenciareg',
                                                    iconCls: 'btnEdit',
                                                    text: 'Modificar'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            width: 59,
                                            align: 'center',
                                            dataIndex: 'ln_exr_codigo',
                                            text: 'Nro.',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 699,
                                            dataIndex: 'ls_exc_descripcion',
                                            text: 'Descripcion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'Ln Gru Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Ls Gru Denominacion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_jgd_codigo',
                                            text: 'Ln Jgd Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 442,
                                            dataIndex: 'ls_jgd_nombre',
                                            text: 'Nombres'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            width: 442,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'ln_reg_codigo'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmupuntaje',
                            layout: 'border',
                            title: 'Resultado y Puntaje',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmuresultado',
                                    store: 'gmo.gmu.resultado.stresultado',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnRetrieveResultado',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: ' ln_nro_fila',
                                            text: ' Ln Nro Fila',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_numero',
                                            text: 'Ln Reg Numero',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_cap_codigo',
                                            text: 'Ln Cap Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_cap_descripcion',
                                            text: 'Capitulo'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_prd_codigo',
                                            text: 'Ln Prd Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_gru_codigo',
                                            text: 'Ln Gru Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ls_gru_denominacion',
                                            text: 'Grupo'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Equipo 1',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'ls_equ_local_des',
                                                    text: 'Nombre'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'ln_equ_gollocal',
                                                    text: 'Goles '
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Equipo 2',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'ls_equ_visitante_des',
                                                    text: 'Nombre'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'ln_equ_golvisita',
                                                    text: 'Goles'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Pronostico',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'ln_equ_gollocalreg',
                                                    text: 'Equipo 1'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'ln_equ_golvisitareg',
                                                    text: 'Equipo 2'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'center',
                                            dataIndex: 'ln_puntaje',
                                            text: 'Puntaje',
                                            format: '00'
                                        }
                                    ],
                                    features: [
                                        {
                                            ftype: 'grouping',
                                            groupHeaderTpl: [
                                                '{name}'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pnlgmuresumen',
                            layout: 'border',
                            title: 'Ranking',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    itemId: 'grdgmuresumen',
                                    store: 'gmo.gmu.resultado.rsresumen',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'Menu de opciones:'
                                                },
                                                {
                                                    xtype: 'tbseparator'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnRetrieveResumen',
                                                    iconCls: 'btnRetrieve',
                                                    text: 'Recuperar'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'rownumberer',
                                            width: 40,
                                            align: 'center',
                                            text: 'Nro.'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'ln_reg_codigo',
                                            text: 'Ln Reg Codigo',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 350,
                                            dataIndex: 'ls_per_nombre',
                                            text: 'Participante'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 135,
                                            dataIndex: 'ls_per_nrodocidentidad',
                                            text: 'Nro. Documento'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'ln_reg_numero',
                                            text: 'Nro. Cartilla',
                                            format: '00'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'ls_trn_denominacion',
                                            text: 'Ls Trn Denominacion'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            align: 'right',
                                            dataIndex: 'ln_puntaje',
                                            text: 'Puntaje'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'west',
                    hidden: true,
                    itemId: 'frmgmuexportar',
                    width: 150,
                    bodyPadding: 10,
                    title: 'My Form',
                    method: 'POST'
                }
            ]
        });

        me.callParent(arguments);
    }

});