/*
 * File: app/mundialito/view/gmo/gmu/registro/winMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.view.gmo.gmu.registro.winMtto', {
    extend: 'Ext.window.Window',

    alternateClassName: [
        'gmo.gmu.registro.winMtto'
    ],
    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Separator',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Hidden',
        'Ext.form.FieldSet',
        'Ext.form.field.Display'
    ],

    height: 190,
    itemId: 'wingmuregistro',
    width: 532,
    layout: 'border',
    title: 'Mantenimiento de Registro de Pronostico',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Menu de opciones:'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            iconCls: 'btnSave',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCerrar',
                            iconCls: 'btnClose',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    itemId: 'frmgmuregistro',
                    bodyPadding: 10,
                    method: 'POST',
                    url: '/library/Mundialito/process/lst_gmu_registro.php',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'ls_per_nombre',
                            fieldLabel: 'Participante',
                            labelAlign: 'top',
                            name: 'ls_per_nombre',
                            readOnly: true
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'accion',
                            fieldLabel: 'Label',
                            name: 'accion'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_per_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_per_codigo'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_reg_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_reg_codigo',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'ln_trn_codigo',
                            fieldLabel: 'Label',
                            name: 'ln_trn_codigo',
                            value: 1
                        },
                        {
                            xtype: 'fieldset',
                            title: 'Nota:',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    value: 'Para crear un nuevo registro de pronostico del Mundial, debe dar click en el boton "Guardar".'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});