/*
 * File: app/mundialito/controller/gmo/gmu/partidoreg/crtMtto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('mundialito.controller.gmo.gmu.partidoreg.crtMtto', {
    extend: 'Ext.app.Controller',

    alternateClassName: [
        'gmo.gmu.partidoreg.crtMtto'
    ],

    views: [
        'gmo.gmu.partidoreg.winMtto'
    ],

    refs: [
        {
            ref: 'Mtto',
            selector: '#winmttopartidoreg'
        },
        {
            ref: 'Main',
            selector: '#vpngmumain'
        }
    ],

    onWinmttopartidoregAfterRender: function(component, eOpts) {
             var me = this,
                 vp = me.getMtto(),
                 ln_reg_codigo=vp.down('#ln_reg_codigo').getValue(),
                 ln_gru_codigo=vp.down('#ln_gru_codigo').getValue(),
                 st_grupo = vp.down('#grdgmupartidoreg').getStore();
                 st_grupo.load({
                     params:{
                         'operacion':2,
                         'accion':2,
                         'ln_reg_codigo':ln_reg_codigo,
                         'ln_gru_codigo':ln_gru_codigo,
                         'ls_condicion':'I'
                     }
                 });

    },

    onBtnguardarClick: function(button, e, eOpts) {
        var me=this,
            win = me.getMtto(),
            vp  = me.getMain(),
            frm = win.down('#frmgmupartidoreg'),
            ln_nro_tab	  = win.down('#ln_nro_tab').getValue(),
            ln_accion	  = win.down('#accion').getValue(),
            ln_reg_codigo = win.down('#ln_reg_codigo').getValue(),
            ln_gru_codigo = win.down('#ln_gru_codigo').getValue(),
            stPartido	  = win.down('#grdgmupartidoreg').getStore(),
            lstPrnCodigo=[],
            lstPrdCodigo=[],
            lstLocal=[],
            lstVisita=[],
            lstGolLocal=[],
            lstGolVisita=[];

        var ls_validacion='1';

        if (frm.isValid()===false){

            Ext.MessageBox.alert('Mensaje','Datos incompletos, favor de revisar');

            return;
        }


        Ext.each(stPartido.getRange(), function(record){
            lstPrnCodigo.push(record.get('ln_prn_codigo'));
            lstPrdCodigo.push(record.get('ln_prd_codigo'));
            lstLocal.push(record.get('ln_equ_local'));
            lstVisita.push(record.get('ln_equ_visitante'));

            if (record.get('ln_equ_gollocal')!==''){
            if (record.get('ln_equ_gollocal')<='-1'){

                ls_validacion='0';

                Ext.MessageBox.alert('Mensaje','No puede existir registro de goles con valor negativo');

                return;

                }
            }

            if (record.get('ln_equ_golvisita')!==''){

            if (record.get('ln_equ_golvisita')<='-1'){

                ls_validacion='0';

                Ext.MessageBox.alert('Mensaje','No puede existir registro de goles con valor negativo');

                return;

            }
            }

            lstGolLocal.push(record.get('ln_equ_gollocal')==='' ? -1 :record.get('ln_equ_gollocal'));
            lstGolVisita.push(record.get('ln_equ_golvisita')==='' ? -1 :record.get('ln_equ_golvisita'));


            if (record.get('ln_gru_tipo')===2){
                if ((record.get('ln_equ_gollocal')!=='') && (record.get('ln_equ_golvisita')!=='')){

                    if (record.get('ln_equ_gollocal')===record.get('ln_equ_golvisita')){

                        ls_validacion='0';

                        Ext.MessageBox.alert('Mensaje','En esta etapa no puede haber empates, tiene que definir un equipo ganador');

                        return;
                    }
                }
            }

        });


        if (ls_validacion==='0'){return;}

        var st_store;

        if(ln_nro_tab==='0') {st_store=vp.down('#grdgmugrupodetreg');}
        if(ln_nro_tab==='1') {st_store=vp.down('#grdgmupartidooctavo');}
        if(ln_nro_tab==='2') {st_store=vp.down('#grdgmupartidocuarto');}
        if(ln_nro_tab==='3') {st_store=vp.down('#grdgmupartidofinal');}


        frm.submit({
            success: function(form, action){

                var objJson =Ext.JSON.decode(action.response.responseText);
                if (objJson.success){
                    Ext.MessageBox.alert('Mensaje',objJson.msg);
                    st_store.getStore().reload();
                    st_store.getSelectionModel().deselectAll();
                    win.close();
                }
            },
            failure: function(form,action){

                var objJson =Ext.JSON.decode(action.response.responseText);

                Ext.MessageBox.alert('Mensaje',objJson.msgError);

            },
            params:{
                'operacion':1,
                'accion':ln_accion,
                'ln_reg_codigo':ln_reg_codigo,
                'lstPrnCodigo[]':lstPrnCodigo,
                'lstPrdCodigo[]':lstPrdCodigo,
                'lstLocal[]':lstLocal,
                'lstVisita[]':lstVisita,
                'lstGolLocal[]':lstGolLocal,
                'lstGolVisita[]':lstGolVisita
            }

        });

    },

    onBtncerrarClick: function(button, e, eOpts) {
            var me=this,

                vp = me.getMain();

                vp.down('#grdgmugrupodetreg').getSelectionModel().deselectAll();

                button.up('#winmttopartidoreg').close();
    },

    init: function(application) {
        this.control({
            "#winmttopartidoreg": {
                afterrender: this.onWinmttopartidoregAfterRender
            },
            "#winmttopartidoreg #btnguardar": {
                click: this.onBtnguardarClick
            },
            "#winmttopartidoreg #btncerrar": {
                click: this.onBtncerrarClick
            }
        });
    }

});
